[QUIC] configure: use quic cross compiler for aarch64
After the upstream changes from "[QTOOL-87319] Merge upstream commits
from Aug. 18 to Oct. 16", the container recipe for aarch64 cross
compilation got updated. When trying to build it (for CI tests), we need
to download debian:11-slim from docker.io, but we unfortunately get
blocked from doing so:

[internal] load metadata for docker.io/library/debian:11-slim
sha256:6e4309eac420162ad8177590ce8500631d65e01efe9982fc4ca27197e60beaba
ERROR: failed to authorize: rpc error: code = Unknown desc = failed to fetch oauth token: unexpected status: 401 Unauthorized

At some point, we should probably switch to QCOM's own docker registry
instance. But for now, let's use one of the cross compilers from the
shared directories so that we can avoid the container problem all
together.

Signed-off-by: Matheus Tavares Bernardino <quic_mathbern@quicinc.com>