Add "unused" attribute to mem_read* HMX placeholders
This will fix failures when building w/clang:

    ../target/hexagon/coproc.c:30:24: error: unused function 'mem_read1' [-Werror,-Wunused-function]
    static inline size1u_t mem_read1(CPUHexagonState *env, paddr_t paddr)

Signed-off-by: Brian Cain <bcain@quicinc.com>