[QTOOL-101912, QTOOL-80108] don't autostart when revcon is on
After the latest upstream merge, we started to see the issue QTOOL-80108
again:

  warning: gdbstub: client sent packet while target running
  error: failed to get reply to handshake packet within timeout of 0.0 seconds

This seems to come from 108e8180c6 (gdbstub: Fix client Ctrl-C handling,
2023-07-11), which allows some untimely stop-reply packets. GDB merely
ignores them, but they do cause an error with hexagon-lldb when using
revcon: lldb starts the connection, the first message pauses the CPU,
and this triggers a stop-reply packet which is not expected by LLDB, and
furthermore an invalid reply to its previous packet.

The change also cause the multiarch GDB test to fail, so this was
reported upstream: https://lore.kernel.org/qemu-devel/456ed3318421dd7946bdfb5ceda7e05332da368c.1690910333.git.quic_mathbern@quicinc.com/

However, it's more likely that the test itself will be adjusted, rather
than the gdbstub. Besides, there is an easier alternative for us, which
doesn't depend on upstream: we simply don't autostart the CPU when
revcon is used. LLDB will issue a 'continue' packet anyways, so let's
start halted and avoid the untimely stop-reply issue to begin with. This
is a better fix for QTOOL-80108.

Signed-off-by: Matheus Tavares Bernardino <quic_mathbern@quicinc.com>